framework:
    asset_mapper:
        paths:
            - assets/
        missing_import_mode: strict
        excluded_patterns:
            - '*/styles/input.css'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
